In [ ]:
import numpy as np 
a = [10,20,12,23,34,45,56,67]
a1 = np.array(a)

In [ ]:
print(type(a1))

<class 'numpy.ndarray'>


In [ ]:
print(a1)

[10 20 12 23 34 45 56 67]


In [ ]:

a = a + 10

TypeError: ignored

In [ ]:
a1 = a1 + 12

In [ ]:
a1

array([22, 32, 24, 35, 46, 57, 68, 79])

In [ ]:
mul = [[0,9,8],[7,6,5],[4,3,2]] 

In [ ]:
mul

[[0, 9, 8], [7, 6, 5], [4, 3, 2]]

In [ ]:
b = np.array(mul)

In [ ]:
b

array([[0, 9, 8],
       [7, 6, 5],
       [4, 3, 2]])

In [ ]:
c = np.array(b, dtype = float)

In [ ]:
c

array([[0., 9., 8.],
       [7., 6., 5.],
       [4., 3., 2.]])

In [ ]:
c.astype(int)

array([[0, 9, 8],
       [7, 6, 5],
       [4, 3, 2]])

In [ ]:
c.astype(str)

array([['0.0', '9.0', '8.0'],
       ['7.0', '6.0', '5.0'],
       ['4.0', '3.0', '2.0']], dtype='<U32')

In [ ]:
c.tolist()

[[0.0, 9.0, 8.0], [7.0, 6.0, 5.0], [4.0, 3.0, 2.0]]

In [ ]:
ml = [[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,12,14,16]]
ml = np.array(ml)

In [ ]:
print(ml)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [10 12 14 16]]


In [ ]:
print("shape is {}".format(ml.shape))
print("size is {}".format(ml.size))
print("datatype is {}".format(ml.dtype))
print("the number of dimensions is {}".format(ml.ndim))

shape is (4, 4)
size is 16
datatype is int64
the number of dimensions is 2


In [ ]:
ml

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 12, 14, 16]])

In [ ]:
ml[:3,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
ml = (ml> 10)

In [ ]:
ml

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [ ]:
ml[ml]

array([ True,  True,  True])

In [ ]:
ml[::-1,]

array([[False,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
infinity = [[1,3,5],[2,4,6],[1,2,8]]
infinity = np.array(infinity)

In [ ]:
infinity 

array([[1, 3, 5],
       [2, 4, 6],
       [1, 2, 8]])

In [ ]:
infinity[::-1,::-1]


array([[8, 2, 1],
       [6, 4, 2],
       [5, 3, 1]])

In [ ]:
ab = np.array(infinity, dtype = float)


In [ ]:
ab[1,2] = np.nan

In [ ]:
ab

array([[ 1.,  3.,  5.],
       [ 2.,  4., nan],
       [ 1.,  2.,  8.]])

In [ ]:
ab[0,0] = np.inf

In [ ]:
ab

array([[inf,  3.,  5.],
       [ 2.,  4., nan],
       [ 1.,  2.,  8.]])

In [ ]:
gb = np.isnan(ab) | np.isinf(ab)
ab[gb] = -1 
ab

array([[-1.,  3.,  5.],
       [ 2.,  4., -1.],
       [ 1.,  2.,  8.]])

In [ ]:
print("the mean value is {}".format(ab.mean()))
print("the max value is {}".format(ab.max()))
print("the min value is {}".format(ab.min()))



the mean value is 2.5555555555555554
the max value is 8.0
the min value is -1.0


In [ ]:
print("column wise minimum: {}".format(np.amin(ab,axis=0)))

column wise minimum: [-1.  2. -1.]


In [ ]:

print("row wise minimum: {}".format(np.amin(ab,axis = 1)))

row wise minimum: [-1. -1.  1.]


In [ ]:

#Cumulative Sum
np.cumsum(ab)

array([-1.,  2.,  7.,  9., 13., 12., 13., 15., 23.])

In [ ]:
abc = ab[:2,:2]  
abc[:1, :1] = 20  
abc

array([[20.,  3.],
       [ 2.,  4.]])

In [ ]:
par = abc[:2, :2].copy()
par[:1, :1] = 1000  
par

array([[1000.,    3.],
       [   2.,    4.]])

In [ ]:
org = np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
org

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
org.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
org.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
d = org.flatten()


In [ ]:
d[1] = 10

In [ ]:
print(org)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
d1 = org.ravel()

In [ ]:
d1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
d1[1] = 12
org

array([[ 1, 12,  3,  4],
       [ 5,  6,  7,  8]])

In [ ]:
print(np.arange(5))
print(np.arange(1,10))
print(np.arange(0,10,2))
print(np.arange(20,0,-5))

[0 1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[20 15 10  5]


In [ ]:
np.linspace(start = 1, stop = 50, num = 5, dtype = int)

array([ 1, 13, 25, 37, 50])

In [ ]:
np.set_printoptions(precision = 3)

np.logspace(start = 10, stop = 100, num = 15, base = 10)

array([1.000e+010, 2.683e+016, 7.197e+022, 1.931e+029, 5.179e+035,
       1.389e+042, 3.728e+048, 1.000e+055, 2.683e+061, 7.197e+067,
       1.931e+074, 5.179e+080, 1.389e+087, 3.728e+093, 1.000e+100])

In [ ]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones([5,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr = [1,2,3,4,5]

print('tile: {}'.format(np.tile(arr,5)))

print('repeat: {}'.format(np.repeat(arr,2)))

tile: [1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]
repeat: [1 1 2 2 3 3 4 4 5 5]


In [ ]:
print(np.random.rand(10,30))
print(np.random.randn(5,5))
print(np.random.randint(0,50, size=[3,4]))
print(np.random.random())
print(np.random.random(size=[3,3]))
print(np.random.choice(['a','b','c','d','e','f'], size = 20 ))
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, .1, 0.1, 0.4, 0.1]))

[[0.157 0.921 0.282 0.261 0.493 0.474 0.867 0.766 0.692 0.674 0.859 0.56
  0.27  0.97  0.452 0.849 0.921 0.022 0.471 0.75  0.45  0.787 0.249 0.324
  0.664 0.474 0.478 0.336 0.449 0.136]
 [0.331 0.974 0.732 0.735 0.49  0.534 0.089 0.366 0.826 0.98  0.046 0.298
  0.998 0.11  0.508 0.777 0.061 0.881 0.173 0.143 0.068 0.876 0.74  0.341
  0.895 0.992 0.402 0.399 0.35  0.074]
 [0.025 0.222 0.462 0.884 0.454 0.753 0.622 0.763 0.868 0.905 0.269 0.315
  0.291 0.833 0.803 0.812 0.912 0.895 0.553 0.671 0.228 0.052 0.986 0.075
  0.116 0.077 0.812 0.437 0.985 0.454]
 [0.838 0.661 0.126 0.529 0.972 0.567 0.518 0.085 0.257 0.265 0.582 0.111
  0.97  0.677 0.627 0.891 0.301 0.777 0.736 0.108 0.974 0.253 0.326 0.967
  0.387 0.041 0.304 0.933 0.387 0.453]
 [0.144 0.163 0.56  0.572 0.403 0.211 0.363 0.465 0.446 0.074 0.985 0.656
  0.333 0.693 0.12  0.614 0.03  0.066 0.043 0.522 0.85  0.82  0.393 0.984
  0.833 0.589 0.872 0.035 0.015 0.847]
 [0.388 0.089 0.093 0.754 0.941 0.81  0.84  0.764 0.775 0.203 0.33

In [ ]:
r1 = np.random.RandomState(50)

print(r1.rand(3,3))

[[0.495 0.228 0.255]
 [0.396 0.377 0.997]
 [0.408 0.772 0.761]]


In [ ]:
np.random.seed(30)

print(np.random.rand(3,3))

[[0.644 0.381 0.663]
 [0.164 0.963 0.347]
 [0.992 0.235 0.586]]


In [ ]:
np.random.seed(50)

a = np.random.randint(0, 20, size = 14)
print(a)

[16  0 11 13  1  4  6  5  6 13  5  2  7 15]


In [ ]:
u,c = np.unique(a, return_counts=True)
print("Unique terms : {}".format(u))
print("counts : {}".format(c))

Unique terms : [ 0  1  2  4  5  6  7 11 13 15 16]
counts : [1 1 1 1 2 2 1 1 2 1 1]


In [ ]:
# Create an array
import numpy as np
arr = np.array([18,3, 27, 17, 10, 2, 5, 2])
print("Array: ", arr)

index = np.where(arr > 5)
print("Positions where value > 5: ", index)

Array:  [18  3 27 17 10  2  5  2]
Positions where value > 5:  (array([0, 2, 3, 4]),)


In [ ]:
arr.take(index)

array([[18, 27, 17, 10]])

In [ ]:
np.where(arr>14,'a','b')

array(['a', 'b', 'a', 'a', 'b', 'b', 'b', 'b'], dtype='<U1')

In [ ]:
print("position of max value: {}".format(np.argmax(arr)))

print("position of min value: {}".format(np.argmin(arr)))

position of max value: 2
position of min value: 5


In [ ]:
np.set_printoptions(suppress= True)

path = 'https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/639388c2cbc2120a14dcf466e85730eb8be498bb/iris.csv'

iris = np.genfromtxt(path, delimiter=',', skip_header=1,filling_values=10, dtype='float')
iris[:10]

array([[ 5.1,  3.5,  1.4,  0.2, 10. ],
       [ 4.9,  3. ,  1.4,  0.2, 10. ],
       [ 4.7,  3.2,  1.3,  0.2, 10. ],
       [ 4.6,  3.1,  1.5,  0.2, 10. ],
       [ 5. ,  3.6,  1.4,  0.2, 10. ],
       [ 5.4,  3.9,  1.7,  0.4, 10. ],
       [ 4.6,  3.4,  1.4,  0.3, 10. ],
       [ 5. ,  3.4,  1.5,  0.2, 10. ],
       [ 4.4,  2.9,  1.4,  0.2, 10. ],
       [ 4.9,  3.1,  1.5,  0.1, 10. ]])

In [ ]:
iris2 = np.genfromtxt(path, delimiter=',', skip_header=1, dtype=None)
iris2[:15] 

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


array([(5.1, 3.5, 1.4, 0.2, b'setosa'), (4.9, 3. , 1.4, 0.2, b'setosa'),
       (4.7, 3.2, 1.3, 0.2, b'setosa'), (4.6, 3.1, 1.5, 0.2, b'setosa'),
       (5. , 3.6, 1.4, 0.2, b'setosa'), (5.4, 3.9, 1.7, 0.4, b'setosa'),
       (4.6, 3.4, 1.4, 0.3, b'setosa'), (5. , 3.4, 1.5, 0.2, b'setosa'),
       (4.4, 2.9, 1.4, 0.2, b'setosa'), (4.9, 3.1, 1.5, 0.1, b'setosa'),
       (5.4, 3.7, 1.5, 0.2, b'setosa'), (4.8, 3.4, 1.6, 0.2, b'setosa'),
       (4.8, 3. , 1.4, 0.1, b'setosa'), (4.3, 3. , 1.1, 0.1, b'setosa'),
       (5.8, 4. , 1.2, 0.2, b'setosa')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S10')])

In [ ]:

np.savetxt("npsavetest.csv", data, delimiter=",")

In [ ]:
ans = np.array([1,2,3,4])
ans.dtype

dtype('int64')

In [ ]:
np.save('ans.npy',ans)  

In [ ]:
a = np.load('ans.npy')
print(a)

[1 2 3 4]


In [ ]:
z = np.zeros([3, 3])
o = np.ones([3, 3])
print(z)
print(o)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
np.concatenate([z,o], axis=0)  
np.vstack([z,o])  
np.r_[z,o] 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.concatenate([z,o], axis=1)  
np.hstack([z,o])  
np.c_[z,o] 

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [ ]:
np.r_[[10,21,32], 10, 20, [34,45,56]]

array([10, 21, 32, 10, 20, 34, 45, 56])

In [ ]:
np1 = np.random.randint(0,50, size=[5, 5])
print(np1)

[[ 4 14 35 28 27]
 [26 26  6 20 43]
 [31 49 21 42 41]
 [ 0  6 19  2 15]
 [30 41 35 26  2]]


In [ ]:

np.sort(np1, axis=0)

array([[ 0,  6,  6,  2,  2],
       [ 4, 14, 19, 20, 15],
       [26, 26, 21, 26, 27],
       [30, 41, 35, 28, 41],
       [31, 49, 35, 42, 43]])

In [ ]:
np.sort(np1, axis=1)

array([[ 4, 14, 27, 28, 35],
       [ 6, 20, 26, 26, 43],
       [21, 31, 41, 42, 49],
       [ 0,  2,  6, 15, 19],
       [ 2, 26, 30, 35, 41]])

In [ ]:
x = np.array([10, 100, 5, 25, 18, 99])
sort_index = np.argsort(x)
print(sort_index)

[2 0 4 3 5 1]


In [ ]:
x[sort_index]

array([  5,  10,  18,  25,  99, 100])

In [ ]:
col = x[:,].argsort()

x[col]

array([  5,  10,  18,  25,  99, 100])

In [ ]:
x[col[::-1]]

array([100,  99,  25,  18,  10,   5])

In [ ]:
ind = np.lexsort((x[:, ], x[:, ])) 
x[ind]

array([  5,  10,  18,  25,  99, 100])

In [ ]:
dt = np.datetime64('2020-02-01 19:00:00')

dt

numpy.datetime64('2020-02-01T19:00:00')

In [ ]:
dt1 = np.datetime64(dt,'D')
dt1

numpy.datetime64('2020-02-01')

In [ ]:

tm = np.timedelta64(100, 'm')  
ts = np.timedelta64(20, 's')  
tes = np.timedelta64(30, 'ns') 

print('Adding days: ', dt + 10)
print('Adding minutes: ', dt + tm)
print('Adding seconds: ', dt + ts)
print('Adding nanoseconds: ', dt + tes)

Adding days:  2020-02-01T19:00:10
Adding minutes:  2020-02-01T20:40:00
Adding seconds:  2020-02-01T19:00:20
Adding nanoseconds:  2020-02-01T19:00:00.000000030


In [ ]:
np.datetime_as_string(dt)

'2020-02-01T19:00:00'

In [ ]:
dates = np.arange(np.datetime64('2020-02-01'), np.datetime64('2020-03-01'))
print(dates)

np.is_busday(dates)

['2020-02-01' '2020-02-02' '2020-02-03' '2020-02-04' '2020-02-05'
 '2020-02-06' '2020-02-07' '2020-02-08' '2020-02-09' '2020-02-10'
 '2020-02-11' '2020-02-12' '2020-02-13' '2020-02-14' '2020-02-15'
 '2020-02-16' '2020-02-17' '2020-02-18' '2020-02-19' '2020-02-20'
 '2020-02-21' '2020-02-22' '2020-02-23' '2020-02-24' '2020-02-25'
 '2020-02-26' '2020-02-27' '2020-02-28' '2020-02-29']


array([False, False,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True, False])

In [ ]:
import datetime
dt = dt.tolist()
dt

datetime.datetime(2020, 2, 1, 19, 0)

In [ ]:
print('Year: ', dt.year)  
print('Day of month: ', dt.day)
print('Month of year: ', dt.month)  
print('Day of Week: ', dt.weekday())

Year:  2020
Day of month:  1
Month of year:  2
Day of Week:  5


In [ ]:
def scalar(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2

print('x = 10 returns ', scalar(100))
print('x = 11 returns ', scalar(15))


x = 10 returns  50.0
x = 11 returns  225


In [ ]:
scala_r = np.vectorize(scalar, otypes=[float])

print('x = [1,2,3] returns ', scala_r([1, 2, 3]))
print('x = [[5, 6, 7], [1, 2, 3]] returns ', scala_r([[5, 6, 7], [1, 2, 3]]))

x = [1,2,3] returns  [1. 1. 9.]
x = [[5, 6, 7], [1, 2, 3]] returns  [[25.  3. 49.]
 [ 1.  1.  9.]]


In [ ]:
np.random.seed(10)
arr_x = np.random.randint(1,10,size=[3,3])
arr_x

array([[5, 1, 2],
       [1, 2, 9],
       [1, 9, 7]])

In [ ]:
x1 = np.arange(20)
print('Where should 10 be inserted?: ', np.searchsorted(x1, 10))
print('Where should 15 be inserted (right)?: ', np.searchsorted(x1, 15, side='right'))

Where should 10 be inserted?:  10
Where should 15 be inserted (right)?:  16


In [ ]:
a = np.arange(10)
bins = np.array([1, 3, 6, 9])


np.digitize(a, bins)

array([0, 1, 1, 2, 2, 2, 3, 3, 3, 4])

In [ ]:
np.clip(x, 3, 8)

array([8, 8, 5, 8, 8, 8])

In [ ]:
x = np.array([1,1,2,2,3,3,3,4,4,4,4]) 
np.bincount(x) 

counts, bins = np.histogram(x, [0, 1, 3, 5, 7])
print('Counts: ', counts)
print('Bins: ', bins)

Counts:  [0 4 7 0]
Bins:  [0 1 3 5 7]
